### ISSUE TITLE
What motivated you to open up an AMA?

### ISSUE THREAD

**Issue by scichelli** [ChrisMissal/ama#1]
Amusing use of GitHub issues. What kind of conversations are you hoping to have here? What do you secretly wish we would ask? Which Hogwarts house would you get sorted into?

**Comment by ChrisMissal** [comment]
I have no idea what kind of questions I'll be asked @scichelli! I saw some others (@una and @iheanyi) on twitter doing it and thought it would be fun. We'll see where it goes! :smile: 

Hogwarts house? I don't know, I never really got into Lord of the Rings, but if I had to choose, how about Jedi?
