### ISSUE TITLE
What do you think about Spain?

### ISSUE THREAD

**Issue by aarroyoc** [ChrisMissal/ama#11]
How do people from outside Spain thinks about Spain? and How do you think about Spain?

**Comment by ChrisMissal** [comment]
I have never been to Spain unfortunately. What I know about it has been largely influenced by friends that have traveled there or lived there for one half and one year in college. I don't know much about what the majority of my peers think of it, but I do have one friend that wants to move there some day.

It sounds like a great place. I was told about the people, the food, the parties ( :beers: :cocktail: ) and that it was a lot of fun. My Spanish is very poor, but I'd love to visit sometime! :es:
