### ISSUE TITLE
What would you make if you had infinite time, energy and zero distractions?

### ISSUE THREAD

**Issue by arthurvr** [ChrisMissal/ama#6]

**Comment by ChrisMissal** [comment]
This one is tough, let me think about it. :smiley:

**Comment by ChrisMissal** [comment]
Great question @arthurvr! After some thought over the past few days, I think I would want to work creating the first attempts at a [Dyson Sphere](https://en.wikipedia.org/wiki/Dyson_sphere).

The problem is that if I had infinite energy, we wouldn't really need one. :smirk:
