### ISSUE TITLE
How do I grow an Epic Beard like yours?

### ISSUE THREAD

**Issue by programatt** [ChrisMissal/ama#9]
I've recently progressed past the peach fuzz facial hair stage. How do I achieve the next level of beard greatness when all I can grow is a solid goatee?

**Comment by ChrisMissal** [comment]
The best two tips for beard growing are actually very similar, yet somewhat contradictory.
1. **Don't cut it** – That's right, you have to keep growing it. There may be places that don't grow in so well, but as it gets longer, these will be covered up. A beard that is just stubble makes those spots highly noticeable and somewhat discouraging. When the hairs get longer, they start to lay flat (mostly) and hide the spots that aren't so great.
2. **Have somebody cut it** – Go to a legit barber shop when it gets longer and needs grooming. They will make you look 5x better and show you where/how to trim your beard to keep it looking nice. When you get your hair cut, get your beard cut. In between though, a small scissors is helpful to keep some of those rogue hairs the right length.

_No facial hair is actually easier to maintain than a beard (unless you're going for a "homeless" look). Beards can and will collect crumbs, food, liquids, etc, and require much more maintenance than a hairless face._

Finally, beards aren't for everybody. If you don't have the follicles in the right places, facial hair might not be right for you. There aren't magic cures, potions, or lotions to make a beard appear out of nowhere.

Thanks for the question @programatt, I had fun answering it! Good luck on your beard growing adventure! :smile:
